# Generated by Django 4.2 on 2023-06-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="create",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="create", name="due_date", field=models.DateTimeField(null=True),
        ),
    ]
